### ISSUE TITLE
Navigate to sub-destination

### ISSUE THREAD

**Issue by tilpap** [Zhuinden/Jetpack-Navigation-Hilt-MultiModule-Example#3]
How would you navigate directly from Splash to a sub-destination of Main? For example in the navigation_main.xml add another fragment ("FooFragment"), that the user would navigate to clicking a button. Could there be a way to use your method navigating directly to FooFragment from Splash?

Thanks!

**Comment by Zhuinden** [comment]
@tilpap If you need to access a subdestination in the realm of Jetpack Navigation's core design, then unfortunately you need a deep link to get there, as you cannot directly access a "subgraph's" inner destinations in any other way. A direct navigation action only goes to the start destination of a nested subgraph. Alternately, you'd need to open the start destination, and also set a flag in a common viewmodel that when main is opened, you immediately navigate to the next screen.

**Comment by tilpap** [comment]
Thanks a lot Gabor! I used deep links. I am a bit afraid of sequential navigation commands with flags due to probable performance issues that would affect user experience (showing the intermediate destination for a bit)
